# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_opreation', '0002_auto_20180213_1329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
    ]
